name = "Program 4"
description = "Simplest possible program"

[[blocks]]
name = "Upper day 1"
description = "Max effort day"

[[blocks.exercises]]
name = "Back Squat"
sets = 3

[[blocks.exercises]]
name = "Bench Press"
sets = 3
