name = "The Berserk"
description = "Designed to turn you into an absolute unit"

[[blocks]]
name = "Upper Day 1"

[[blocks.exercises]]
name = "Bench Press"
sets = 3
reps = ["4-8", "4-8", "6-8"]

[[blocks.exercises]]
name = "Bent Over Row"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Machine Incline Press"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Weighted Pull-Up"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Smith JM Press"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "Machine Preacher Curl"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "Dumbbell Lateral Raise"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "Standing Unilateral Smith Calf Raise"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks]]
name = "Lower Day 1"

[[blocks.exercises]]
name = "High Bar Squat"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "RDL"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Leg Extension"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Lying Leg Curl"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Machine Ab Crunch"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Leg Press Calf Raise"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "Unilateral Cable Wrist Curl"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks]]
name = "Upper Day 2"

[[blocks.exercises]]
name = "Barbell Overhead Press"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Weighted Pull-Up"
sets = 2
reps = ["3-6", "3-6"]

[[blocks.exercises]]
name = "Machine Incline Press"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Machine Row"
sets = 2
reps = ["4-8", "4-8"]
options = ["Cable Row"]

[[blocks.exercises]]
name = "Machine Preacher Curl"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Smith JM Press"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Cable Hammer Curl"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Tricep Pushdown"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Unilateral Cable Wrist Curl"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks]]
name = "Lower Day 2"

[[blocks.exercises]]
name = "Paused High Bar Squat"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Seated Leg Curl"
sets = 3
reps = ["4-8", "4-8", "AMRAP"]

[[blocks.exercises]]
name = "Leg Extension"
sets = 2
reps = ["4-8", "4-8"]
options = ["Sissy Squat"]

[[blocks.exercises]]
name = "Machine Ab Crunch"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Standing Unilateral Smith Calf Raise"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "Unilateral Cable Wrist Curl"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks]]
name = "Upper Day 3"

[[blocks.exercises]]
name = "Bench Press"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Machine Row"
sets = 2
reps = ["4-8", "4-8"]
options = ["Cable Row"]

[[blocks.exercises]]
name = "Barbell Skull Crusher"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "EZ Bar Preacher Curl"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Tricep Pushdown"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Reverse EZ Bar Curl"
sets = 2
reps = ["4-8", "4-8"]

[[blocks.exercises]]
name = "Seated Dumbbell Lateral Raise"
sets = 3
reps = ["4-8", "4-8", "4-8"]

[[blocks.exercises]]
name = "Cable Wrist Curl"
sets = 3
reps = ["4-8", "4-8", "4-8"]

